name: Betavue
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60035
title: Betavue Creative Agency
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#396103'
    - '#264d02'
    - '#182c01'
    - '#538b06'
    - '#8bb319'
  brandStrength: 0.4375
  lightness: 0.3125
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
