name: Betavue
favicon: null
layout_spectrum: 0.28978434996679425
typography_spectrum: 0.2489702757447958
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.37078632111661136
  lightness: 0.21021231589838862
  saturation: 0.18077332992106676
  rhythmicContrast: 0.28479640651494265
purpose: []
